defmodule Legistar.Api.Matter do
  @moduledoc false

  # TODO: exclude the MatterId field for creating a matter
  @derive {Poison.Encoder, except: [:MatterId]}

  @type t :: %__MODULE__{
    MatterId: Integer.t,
    MatterGuid: String.t,
    MatterLastModifiedUtc: DateTime.t,
    MatterRowVersion: binary,
    MatterFile: String.t,
    MatterName: String.t,
    MatterTitle: String.t,
    MatterTypeId: Integer.t,
    MatterTypeName: String.t,
    MatterStatusId: Integer.t,
    MatterStatusName: String.t,
    MatterBodyId: Integer.t,
    MatterBodyName: String.t,
    MatterIntroDate: DateTime.t,
    MatterAgendaDate: DateTime.t,
    MatterPassedDate: DateTime.t,
    MatterEnactmentDate: DateTime.t,
    MatterEnactmentNumber: String.t,
    MatterRequester: String.t,
    MatterNotes: String.t,
    MatterVersion: String.t,
    MatterText1: String.t,
    MatterText2: String.t,
    MatterText3: String.t,
    MatterText4: String.t,
    MatterText5: String.t,
    MatterDate1: DateTime.t,
    MatterDate2: DateTime.t,
    MatterEXText1: String.t,
    MatterEXText2: String.t,
    MatterEXText3: String.t,
    MatterEXText4: String.t,
    MatterEXText5: String.t,
    MatterEXText6: String.t,
    MatterEXText7: String.t,
    MatterEXText8: String.t,
    MatterEXText9: String.t,
    MatterEXText10: String.t,
    MatterEXDate1: DateTime.t,
    MatterEXDate2: DateTime.t,
    MatterEXDate3: DateTime.t,
    MatterEXDate4: DateTime.t,
    MatterEXDate5: DateTime.t,
    MatterEXDate6: DateTime.t,
    MatterEXDate7: DateTime.t,
    MatterEXDate8: DateTime.t,
    MatterEXDate9: DateTime.t,
    MatterEXDate10: DateTime.t
  }

  @enforce_keys [
    :MatterFile,
    :MatterTypeId,
    :MatterStatusId,
    :MatterBodyId
  ]

  defstruct [
    :MatterId,
    :MatterGuid,
    :MatterLastModifiedUtc,
    :MatterRowVersion,
    :MatterFile,
    :MatterName,
    :MatterTitle,
    :MatterTypeId,
    :MatterTypeName,
    :MatterStatusId,
    :MatterStatusName,
    :MatterBodyId,
    :MatterBodyName,
    :MatterIntroDate,
    :MatterAgendaDate,
    :MatterPassedDate,
    :MatterEnactmentDate,
    :MatterEnactmentNumber,
    :MatterRequester,
    :MatterNotes,
    :MatterVersion,
    :MatterText1,
    :MatterText2,
    :MatterText3,
    :MatterText4,
    :MatterText5,
    :MatterDate1,
    :MatterDate2,
    :MatterEXText1,
    :MatterEXText2,
    :MatterEXText3,
    :MatterEXText4,
    :MatterEXText5,
    :MatterEXText6,
    :MatterEXText7,
    :MatterEXText8,
    :MatterEXText9,
    :MatterEXText10,
    :MatterEXDate1,
    :MatterEXDate2,
    :MatterEXDate3,
    :MatterEXDate4,
    :MatterEXDate5,
    :MatterEXDate6,
    :MatterEXDate7,
    :MatterEXDate8,
    :MatterEXDate9,
    :MatterEXDate10
  ]
end
